name: FF Challenge tests

on:
  push:
    branches: [ develop ]

jobs:
  wpcs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: php-actions/composer@v1
    - name: Run WPCS...
      run: ./vendor/bin/phpcs --standard=WordPress ./ffc-app