name: PHPUnit

on:
  push:
    branches: [ master ]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: php-actions/composer@v1
    - name: Run PHPUnit
      run: ./vendor/bin/phpunit
